### ISSUE TITLE
Scope Zoom control not working

### ISSUE THREAD

**Issue by l0ner** [dsharlet/LiveSPICE#41]
As in the title. Currently clicking on +/- buttons is scope do nothing, and the scope instead adapts the display to currently selected singal, thus removing from display offset singals and/or not displaying fully other singals.

**Comment by dsharlet** [comment]
Hi, sorry to hear you are having trouble. Here are a few things that might help:

- Does the mouse wheel work for you? This should also work to zoom in/out on the scope signals. I think the problem is that the +/- buttons only become activated with the scope control is in focus. Clicking on it will do this.

- However, this only zooms horizontally. The scope always tries to view a particular signal vertically. You can choose the signal to focus on by clicking on a probe in the schematic, or from the dropdown list in the scope control. Other signals will still be visible, but the scope won't focus on those signals.
